export interface LogSheetParametersResponse {
    avgLineNeutralVolt: string,
    avgLineToLineVolt: string,
    bPhaseVolt: string,
    brPhaseVolt: string,
    hourMinSecRun: string,
    inletFlow: string,
    inletTotal: string,
    levelOil: string,
    levelWater: string,
    outletFlow: string,
    outletTotal:string,
    pressureAir: string,
    pressureHighBank:string,
    pressureHighOil: string,
    pressureLowOil: string,
    pressureMediumBank: string,
    pressureWater: string,
    rPhaseVolt: string,
    ryPhaseVolt: string,
    stage1: string,
    stage2: string,
    suctionPressure: string,
    temperatureOil: string,
    temperatureWater: string,
    timeReceived: string,
    totalKw: string,
    yPhaseVolt: string,
    ybPhaseVolt: string,
    
}
